# actions (ros2 run or ros2 launch) or system command:
string action

# ROS namespace where the program is executed
# temoto_namespace of the process manager if empty string is given
string ros_namespace

# name of the package
string package_name

# name of the node or launch file
string executable

# additional arguments
string args

rr_interfaces/TemotoRequestMetadata temoto_metadata
---

# The process id of the loaded resource
int32 pid

rr_interfaces/TemotoResponseMetadata temoto_metadata
